version: '3.5'

services:
  consumer-postgres:
    image: postgres:13
    container_name: 'consumer-postgres'
    # ports:
    #   - "5432:5432"
    env_file:
      - ./consumer/postgres.env
    networks:
      - reach-ids-example
    # volumes:
    #   - connector-data:/var/lib/postgresql/data

  consumer:
    image: ghcr.io/international-data-spaces-association/dataspace-connector
    container_name: 'consumer-connector'
    # ports:
    #   - 8080:8080
    env_file:
      - ./consumer/connector.env
    networks:
      - reach-ids-example
    depends_on:
      - consumer-postgres

  provider-postgres:
    image: postgres:13
    container_name: 'provider-postgres'
    # ports:
    #   - "5432:5432"
    env_file:
      - ./provider/postgres.env
    networks:
      - reach-ids-example
    # volumes:
    #   - connector-data:/var/lib/postgresql/data

  provider:
    image: ghcr.io/international-data-spaces-association/dataspace-connector
    container_name: 'provider-connector'
    # ports:
    #   - 8080:8080
    env_file:
      - ./provider/connector.env
    networks:
      - reach-ids-example
    depends_on:
      - provider-postgres

  proxy:
    image: nginx:1.20
    container_name: 'proxy'
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reach-ids-example
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./consumer/certs/:/certs/consumer/
      - ./provider/certs/:/certs/provider/
    depends_on:
      - consumer
      - provider

networks:
  reach-ids-example:

# volumes:
#   connector-data: {}